# Generated by Django 6.0.2 on 2026-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='arquivo_amostra',
            field=models.FileField(blank=True, null=True, upload_to='amostras_produtos/'),
        ),
    ]
