# Generated by Django 6.0.2 on 2026-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_produto_arquivo_amostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='origem_venda',
            field=models.CharField(default='vitrine', max_length=50),
        ),
    ]
